SPUNIT_EXAMPLE_APPLICATION = $(SPUNIT_BINARY_DIRECTORY)/spunit-examples

$(SPUNIT_EXAMPLE_APPLICATION): $(SPUNIT_EXAMPLE_OUTPUT_FILES) $(SPUNIT_LIBRARY) 
	$(SPUNIT_CPP) $(SPUNIT_CPP_FLAGS) $(SPUNIT_INCLUDE) -o $@ $(SPUNIT_EXAMPLE_OUTPUT_FILES) -L$(SPUNIT_BINARY_DIRECTORY) -lspunit

spunit/examples: SPUNIT_CPP_FLAGS += $(SPUNIT_CPP_DEBUG_FLAGS)
spunit/examples: SPUNIT_INCLUDE += -I$(SPUNIT_EXAMPLES_DIRECTORY)
spunit/examples: $(SPUNIT_EXAMPLE_APPLICATION)

spunit/examples/run: spunit/examples
	@$(SPUNIT_EXAMPLE_APPLICATION) --spunit-reporter=spec --spunit-stream-color=windows