SPUNIT_SOURCE_FILES +=	$(SPUNIT_SOURCE_DIRECTORY)/common/common_flags.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/common/delegate.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/common/runnable.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/fixture/fixture.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/fixture/global_fixture.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/fixture/fixture_section.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/fixture/before_each.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/fixture/after_each.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/fixture/before.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/fixture/after.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/fixture/fixture_scenario_attorney.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/fixture/fixture_before_each_attorney.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/fixture/fixture_after_each_attorney.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/fixture/fixture_before_attorney.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/fixture/fixture_after_attorney.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/scenario/scenario.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/scenario/scenario_status.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/scenario/scenario_delegate.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/scenario/scenario_delegate_utilities.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/runner/runner.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/runner/runner_reporter_attorney.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/runner/stream_reporter_attorney.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/runner/reporter.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/runner/aggregate_reporter.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/runner/null_reporter.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/runner/spec_reporter.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/runner/aggregate_output_stream.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/runner/cout_output_stream.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/runner/cout_output_stream_color_support_none.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/runner/cout_output_stream_color_support_ansi8.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/runner/null_output_stream.cpp\
						$(SPUNIT_SOURCE_DIRECTORY)/spunit_main.cpp
						